zuul:
  ignored-services: "*"
  routes:
    customer:
      path: /customer/**
      service-id: customer-service
      strip-prefix: false
    google:
      path: /google/**
      url : https://google.com
